import csv
import io
import os
import re

from playwright.sync_api import expect, sync_playwright


def complete_validation_csv(blank_csv: str) -> str:
    source = io.StringIO(blank_csv)
    reader = csv.DictReader(source)
    output = io.StringIO()
    writer = csv.DictWriter(output, fieldnames=reader.fieldnames or [])
    writer.writeheader()

    for row in reader:
        row["reviewerId"] = f"coach-{row['reviewerSlot']}"
        row["relevance"] = "5"
        row["timingAccuracy"] = "5"
        row["drillFit"] = "5"
        row["safetyLanguage"] = "5"
        row["status"] = "reviewed"
        if "notes" in row:
            row["notes"] = "Smoke reviewed"
        writer.writerow(row)

    return output.getvalue()


def main() -> None:
    base_url = os.environ.get("MOVEBETA_SMOKE_URL", "http://127.0.0.1:8083")
    console_errors: list[str] = []
    page_errors: list[str] = []

    with sync_playwright() as playwright:
        browser = playwright.chromium.launch(headless=True)
        page = browser.new_page(viewport={"width": 390, "height": 844})
        page.on("console", lambda message: console_errors.append(message.text) if message.type == "error" else None)
        page.on("pageerror", lambda error: page_errors.append(str(error)))
        page.goto(base_url)
        page.wait_for_load_state("networkidle")

        expect(page.get_by_text("On-device climbing coach")).to_be_visible()
        expect(page.get_by_text("Capture a climbing attempt")).to_be_visible()
        expect(page.get_by_text("Session metadata")).to_be_visible()
        expect(page.get_by_text("Capture setup")).to_be_visible()
        expect(page.get_by_text("Setup ready")).to_be_visible()
        expect(page.get_by_label("People: Clear")).to_be_visible()
        expect(page.get_by_label("Gym or wall")).to_be_visible()
        expect(page.get_by_label("Grade or focus")).to_be_visible()
        expect(page.get_by_text("Record", exact=True)).to_be_visible()
        expect(page.get_by_text("Import", exact=True)).to_be_visible()
        expect(page.get_by_text("Demo sources")).to_be_visible()
        expect(page.get_by_text("Analysis quality")).to_be_visible()
        expect(page.get_by_text("Ready for coaching")).to_be_visible()
        expect(page.get_by_text("Beta replay plan")).to_be_visible()
        expect(page.get_by_text("Reduce bent-arm time").first).to_be_visible()
        expect(page.get_by_text("Movement phases")).to_be_visible()
        expect(page.get_by_text("Primary phase:")).to_be_visible()
        expect(page.get_by_text("Cue trust")).to_be_visible()
        expect(page.get_by_text("Validation: pending")).to_be_visible()
        expect(page.get_by_text("Movement metrics")).to_be_visible()
        expect(page.get_by_text("Coach cues")).to_be_visible()

        page.get_by_text("Vertical sequence repeat").click()
        page.wait_for_load_state("networkidle")
        expect(page.get_by_text("Vertical sequence repeat")).to_be_visible()
        expect(page.get_by_text("local-fixture")).to_be_visible()

        page.get_by_role("tab", name="Drills").click()
        page.wait_for_load_state("networkidle")
        expect(page.get_by_text("Practice from evidence")).to_be_visible()
        expect(page.get_by_text("Weekly drill plan")).to_be_visible()
        expect(page.get_by_text("Feedback").first).to_be_visible()
        expect(page.get_by_text("untested").first).to_be_visible()
        expect(page.get_by_text("Practice log").first).to_be_visible()
        expect(page.get_by_text("not logged").first).to_be_visible()
        page.get_by_text("Done", exact=True).first.click()
        expect(page.get_by_text("completed").first).to_be_visible()
        page.get_by_text("Skip", exact=True).nth(1).click()
        page.get_by_text("Skip", exact=True).nth(2).click()
        expect(page.get_by_text("skipped").first).to_be_visible()
        expect(page.get_by_text("Coach pack preview")).to_be_visible()
        expect(page.get_by_text("Plan access").first).to_be_visible()
        expect(page.get_by_text("Unlocks with Pro")).to_be_visible()

        page.set_viewport_size({"width": 1280, "height": 900})
        page.get_by_role("tab", name="Analyze").click()
        page.wait_for_load_state("networkidle")
        expect(page.get_by_text("Capture a climbing attempt")).to_be_visible()
        page.get_by_label("Gym or wall").fill("MoonBoard Room")
        page.get_by_label("Grade or focus").fill("7a")
        page.get_by_label("View: Diagonal").click()
        expect(page.get_by_text("Setup can improve")).to_be_visible()
        page.get_by_label("View: Side On").click()
        expect(page.get_by_text("Clip ready")).to_be_visible()
        expect(page.get_by_text("Analysis quality")).to_be_visible()
        expect(page.get_by_text("Ready for coaching")).to_be_visible()
        expect(page.get_by_text("Beta replay plan")).to_be_visible()
        expect(page.get_by_text("Movement phases")).to_be_visible()
        expect(page.get_by_text("Cue trust")).to_be_visible()
        expect(page.get_by_text("Movement metrics")).to_be_visible()

        page.get_by_role("tab", name="Progress").click()
        page.wait_for_load_state("networkidle")
        expect(page.get_by_text("Technique trends")).to_be_visible()
        expect(page.get_by_text("Next session plan")).to_be_visible()
        expect(page.get_by_text("Target", exact=True).first).to_be_visible()
        expect(page.get_by_text("Technique readiness")).to_be_visible()
        expect(page.get_by_text("Next action")).to_be_visible()
        expect(page.get_by_text("Personal benchmarks")).to_be_visible()
        expect(page.get_by_text("Best overall")).to_be_visible()
        expect(page.get_by_text("Cue patterns")).to_be_visible()
        expect(page.get_by_text("Latest cues")).to_be_visible()
        expect(page.get_by_text("Cue usefulness")).to_be_visible()
        expect(page.get_by_text("No cue feedback yet")).to_be_visible()
        expect(page.get_by_text("Practice consistency")).to_be_visible()
        expect(page.get_by_text("Completion", exact=True)).to_be_visible()
        expect(page.get_by_text("Status blocked")).to_be_visible()
        expect(page.get_by_text("Practice reset session")).to_be_visible()
        expect(page.get_by_text("Attempt comparison")).to_be_visible()
        expect(page.get_by_text("Current trend")).to_be_visible()
        expect(page.get_by_text("Pro history preview")).to_be_visible()
        expect(page.get_by_text("Plan access").first).to_be_visible()

        page.get_by_role("tab", name="Sessions").click()
        page.wait_for_load_state("networkidle")
        expect(page.get_by_text("Local attempts", exact=True)).to_be_visible()
        expect(page.get_by_text("Session review")).to_be_visible()
        expect(page.get_by_text("Focus metric")).to_be_visible()
        expect(page.get_by_text("Primary cue")).to_be_visible()
        expect(page.get_by_text("Timeline", exact=True).first).to_be_visible()
        expect(page.get_by_text("Local evidence")).to_be_visible()
        expect(page.get_by_text("Training log", exact=True)).to_be_visible()
        expect(page.get_by_text("Repeat outcome", exact=True)).to_be_visible()
        expect(page.get_by_text("Cue feedback", exact=True)).to_be_visible()
        page.get_by_label("Project status Repeat").click()
        page.get_by_label("Effort 4").click()
        page.get_by_label("Confidence 5").click()
        page.get_by_label("Repeat outcome Improved").click()
        page.get_by_label("Repeat attempts 2").click()
        page.get_by_label(re.compile("Resolved cue")).first.click()
        page.get_by_text("Useful", exact=True).first.click()
        page.get_by_label("Private training note").fill("Left hip in before the crux.")
        page.get_by_label("Training log tags").fill("board, crux")
        page.get_by_text("Save", exact=True).click()
        page.get_by_role("tab", name="Progress").click()
        page.wait_for_load_state("networkidle")
        expect(page.get_by_text("History filters")).to_be_visible()
        page.get_by_label("vertical", exact=True).click()
        expect(page.get_by_text("1 active filters")).to_be_visible()
        page.get_by_label("Clear progress filters").click()
        expect(page.get_by_text("Project queue")).to_be_visible()
        expect(page.get_by_text("Useful rate")).to_be_visible()
        expect(page.get_by_text("Repeat outcomes")).to_be_visible()
        expect(page.get_by_text("Success", exact=True)).to_be_visible()
        expect(page.get_by_text("Improved 1")).to_be_visible()
        expect(page.get_by_text("Next repeat", exact=True)).to_be_visible()
        expect(page.get_by_text("confidence 5/5")).to_be_visible()
        page.get_by_role("tab", name="Drills").click()
        page.wait_for_load_state("networkidle")
        expect(page.get_by_text("reinforce").first).to_be_visible()
        expect(page.get_by_text("marked useful").first).to_be_visible()
        page.get_by_role("tab", name="Sessions").click()
        page.wait_for_load_state("networkidle")
        expect(page.get_by_text("Coach packet", exact=True).nth(0)).to_be_visible()
        page.get_by_text("Coach packet", exact=True).nth(0).click()
        expect(page.get_by_text("Consent required")).to_be_visible()
        page.get_by_text("Consent", exact=True).nth(0).click()
        expect(page.get_by_text("Coach library")).to_be_visible()
        expect(page.get_by_text("Consented packets")).to_be_visible()
        expect(page.get_by_text("Ready packets")).to_be_visible()
        expect(page.get_by_text("Raw video included: no")).to_be_visible()
        expect(page.get_by_text("Team templates")).to_be_visible()
        expect(page.get_by_text("Privacy-safe packet review")).to_be_visible()
        page.get_by_text("Export library", exact=True).click()
        expect(page.get_by_text("Prepared coach library export")).to_be_visible()
        expect(page.get_by_label("Share prepared export")).to_be_visible()
        expect(page.get_by_text('"schemaVersion": "movebeta.coach-library-export.v1"')).to_be_visible()
        expect(page.get_by_text('"privateNotesIncluded": false')).to_be_visible()
        expect(page.get_by_text('"templates"')).to_be_visible()
        page.get_by_text("Validation seed", exact=True).click()
        expect(page.get_by_text("Prepared cue validation seed")).to_be_visible()
        expect(page.get_by_text('"schemaVersion": "movebeta.cue-validation-study-seed.v1"')).to_be_visible()
        expect(page.get_by_text('"reviewerScoresInvented": false')).to_be_visible()
        expect(page.get_by_text('"reviewTasks"')).to_be_visible()
        page.get_by_text("Review worksheet", exact=True).click()
        expect(page.get_by_text("Prepared cue validation worksheet")).to_be_visible()
        expect(page.get_by_text('"schemaVersion": "movebeta.cue-validation-review-worksheet.v1"')).to_be_visible()
        expect(page.get_by_text('"reviewerId": null')).to_be_visible()
        expect(page.get_by_text('"rowCount"')).to_be_visible()
        page.get_by_text("Worksheet CSV", exact=True).click()
        expect(page.get_by_text("Prepared cue validation worksheet CSV")).to_be_visible()
        completed_csv_input = page.get_by_label("Completed cue validation worksheet CSV")
        expect(completed_csv_input).to_have_value(re.compile("worksheetRowId,clipId,packetReportId"))
        expect(completed_csv_input).to_have_value(re.compile("awaiting-real-review"))
        completed_csv_input.fill(complete_validation_csv(completed_csv_input.input_value()))
        page.get_by_text("Build dataset", exact=True).click()
        expect(page.get_by_text("Prepared cue validation dataset")).to_be_visible()
        expect(page.get_by_text("Validation gate: needs data")).to_be_visible()
        expect(page.get_by_text("At least 20 consented clips are required.")).to_be_visible()
        expect(page.get_by_text('"schemaVersion": "movebeta.cue-validation-dataset.v1"')).to_be_visible()
        expect(page.get_by_text('"reviewerId": "coach-1"')).to_be_visible()
        page.get_by_text("Coach packet", exact=True).nth(0).click()
        expect(page.get_by_text("Prepared coach packet")).to_be_visible()
        expect(page.get_by_text('"athleteContext"')).to_be_visible()
        expect(page.get_by_text('"drillPractice"')).to_be_visible()
        expect(page.get_by_text('"privateNoteIncluded": false')).to_be_visible()
        expect(page.get_by_text('"noteIncluded": false')).to_be_visible()
        expect(page.get_by_text('"schemaVersion": "movebeta.coach-review.v2"')).to_be_visible()
        expect(page.get_by_text('"cueTrust"')).to_be_visible()
        expect(page.get_by_text('"repeatOutcome"')).to_be_visible()

        page.get_by_role("tab", name="Plan").click()
        page.wait_for_load_state("networkidle")
        expect(page.get_by_text("Plan catalog")).to_be_visible()
        expect(page.get_by_text("Current plan").first).to_be_visible()
        expect(page.get_by_text("Upgrade path")).to_be_visible()
        expect(page.get_by_text("Capability matrix")).to_be_visible()
        expect(page.get_by_text("Launch readiness")).to_be_visible()
        expect(page.get_by_text("1/3 launch tracks ready")).to_be_visible()
        expect(page.get_by_text("Stakeholder demo", exact=True)).to_be_visible()
        expect(page.get_by_text("Internal native beta", exact=True)).to_be_visible()
        expect(page.get_by_text("Store submission", exact=True)).to_be_visible()
        expect(page.get_by_text("Real cue-validation dataset")).to_be_visible()
        expect(page.get_by_text("Native QA evidence kit")).to_be_visible()
        expect(page.get_by_text("device runs", exact=True)).to_be_visible()
        expect(page.get_by_text("workflows", exact=True)).to_be_visible()
        expect(page.get_by_text("Template placeholders are rejected by the native QA validator.")).to_be_visible()
        expect(page.get_by_text("Android physical device")).to_be_visible()
        expect(page.get_by_text("iOS physical device")).to_be_visible()
        expect(page.get_by_text("Commercial readiness")).to_be_visible()
        expect(page.get_by_text("Provider status")).to_be_visible()
        expect(page.get_by_text("Not connected")).to_be_visible()

        page.get_by_role("tab", name="Privacy").click()
        page.wait_for_load_state("networkidle")
        expect(page.get_by_text("No upload by default")).to_be_visible()
        expect(page.get_by_text("Airplane-mode readiness")).to_be_visible()
        page.get_by_text("Check", exact=True).click()
        expect(page.get_by_text("Ready for offline analysis")).to_be_visible()
        expect(page.get_by_text("Diagnostics")).to_be_visible()
        page.get_by_text("Prepare", exact=True).click()
        expect(page.get_by_text("Privacy-safe support packet")).to_be_visible()
        expect(page.get_by_text('"excludedArtifacts"')).to_be_visible()
        expect(page.get_by_text("Data portability")).to_be_visible()
        page.get_by_text("Backup", exact=True).click()
        expect(page.get_by_text("Local backup JSON")).to_be_visible()
        expect(page.get_by_role("textbox", name="Local backup JSON")).to_have_value(re.compile('"schemaVersion"'))
        expect(page.get_by_role("textbox", name="Local backup JSON")).to_have_value(re.compile('"drillPractice"'))
        page.get_by_text("Restore backup", exact=True).click()
        expect(page.get_by_text("Status: restored")).to_be_visible()
        expect(page.get_by_text("Reports restored:")).to_be_visible()
        expect(page.get_by_text("Drill practice records restored:")).to_be_visible()

        page.get_by_role("tab", name="Sessions").click()
        page.wait_for_load_state("networkidle")
        page.get_by_label("Delete Vertical sequence repeat").first.click()
        expect(page.get_by_text("Local deletion receipt")).to_be_visible()
        expect(page.get_by_text("Private training log: deleted")).to_be_visible()
        expect(page.get_by_text("Coach consent record: deleted")).to_be_visible()
        expect(page.get_by_text("Video left device: no").last).to_be_visible()

        browser.close()

    if page_errors:
      raise AssertionError(f"Page errors: {page_errors}")
    if console_errors:
      ignored = [item for item in console_errors if "favicon" not in item.lower()]
      if ignored:
        raise AssertionError(f"Console errors: {ignored}")


if __name__ == "__main__":
    main()
