import csv
import io
import os
import re

from playwright.sync_api import expect, sync_playwright


def complete_validation_csv(blank_csv: str) -> str:
    source = io.StringIO(blank_csv)
    reader = csv.DictReader(source)
    output = io.StringIO()
    writer = csv.DictWriter(output, fieldnames=reader.fieldnames or [])
    writer.writeheader()

    for row in reader:
        row["reviewerId"] = f"coach-{row['reviewerSlot']}"
        row["relevance"] = "5"
        row["timingAccuracy"] = "5"
        row["drillFit"] = "5"
        row["safetyLanguage"] = "5"
        row["status"] = "reviewed"
        if "notes" in row:
            row["notes"] = "Smoke reviewed"
        writer.writerow(row)

    return output.getvalue()


def main() -> None:
    base_url = os.environ.get("MOVEBETA_SMOKE_URL", "http://127.0.0.1:8083")
    console_errors: list[str] = []
    page_errors: list[str] = []

    with sync_playwright() as playwright:
        browser = playwright.chromium.launch(headless=True)
        page = browser.new_page(viewport={"width": 390, "height": 844})
        page.on("console", lambda message: console_errors.append(message.text) if message.type == "error" else None)
        page.on("pageerror", lambda error: page_errors.append(str(error)))
        page.goto(base_url)
        page.wait_for_load_state("networkidle")

        expect(page.get_by_text("On-device climbing coach")).to_be_visible()
        expect(page.get_by_text("Capture a climbing attempt")).to_be_visible()
        expect(page.get_by_text("Session metadata")).to_be_visible()
        expect(page.get_by_text("Capture setup")).to_be_visible()
        expect(page.get_by_text("Setup ready")).to_be_visible()
        expect(page.get_by_label("People: Clear")).to_be_visible()
        expect(page.get_by_label("Gym or wall")).to_be_visible()
        expect(page.get_by_label("Grade or focus")).to_be_visible()
        expect(page.get_by_text("Record", exact=True)).to_be_visible()
        expect(page.get_by_text("Import", exact=True)).to_be_visible()
        expect(page.get_by_text("Demo sources")).to_be_visible()
        expect(page.get_by_text("Analysis quality")).to_be_visible()
        expect(page.get_by_text("Ready for coaching")).to_be_visible()
        expect(page.get_by_text("Beta replay plan")).to_be_visible()
        expect(page.get_by_text("Reduce bent-arm time").first).to_be_visible()
        expect(page.get_by_text("Movement phases")).to_be_visible()
        expect(page.get_by_text("Primary phase:")).to_be_visible()
        expect(page.get_by_text("Cue trust")).to_be_visible()
        expect(page.get_by_text("Validation: pending")).to_be_visible()
        expect(page.get_by_text("Movement metrics")).to_be_visible()
        expect(page.get_by_text("Coach cues")).to_be_visible()

        page.get_by_text("Vertical sequence repeat").click()
        page.wait_for_load_state("networkidle")
        expect(page.get_by_text("Vertical sequence repeat")).to_be_visible()
        expect(page.get_by_text("local-fixture")).to_be_visible()

        page.get_by_role("tab", name="Drills").click()
        page.wait_for_load_state("networkidle")
        expect(page.get_by_text("Practice from evidence")).to_be_visible()
        expect(page.get_by_text("Weekly drill plan")).to_be_visible()
        expect(page.get_by_text("Feedback").first).to_be_visible()
        expect(page.get_by_text("untested").first).to_be_visible()
        expect(page.get_by_text("Practice log").first).to_be_visible()
        expect(page.get_by_text("not logged").first).to_be_visible()
        page.get_by_text("Done", exact=True).first.click()
        expect(page.get_by_text("completed").first).to_be_visible()
        page.get_by_text("Skip", exact=True).nth(1).click()
        page.get_by_text("Skip", exact=True).nth(2).click()
        expect(page.get_by_text("skipped").first).to_be_visible()
        expect(page.get_by_text("Coach pack preview")).to_be_visible()
        expect(page.get_by_text("Plan access").first).to_be_visible()
        expect(page.get_by_text("Unlocks with Pro")).to_be_visible()

        page.set_viewport_size({"width": 1280, "height": 900})
        page.get_by_role("tab", name="Analyze").click()
        page.wait_for_load_state("networkidle")
        expect(page.get_by_text("Capture a climbing attempt")).to_be_visible()
        page.get_by_label("Gym or wall").fill("MoonBoard Room")
        page.get_by_label("Grade or focus").fill("7a")
        page.get_by_label("View: Diagonal").click()
        expect(page.get_by_text("Setup can improve")).to_be_visible()
        page.get_by_label("View: Side On").click()
        expect(page.get_by_text("Clip ready")).to_be_visible()
        expect(page.get_by_text("Analysis quality")).to_be_visible()
        expect(page.get_by_text("Ready for coaching")).to_be_visible()
        expect(page.get_by_text("Beta replay plan")).to_be_visible()
        expect(page.get_by_text("Movement phases")).to_be_visible()
        expect(page.get_by_text("Cue trust")).to_be_visible()
        expect(page.get_by_text("Movement metrics")).to_be_visible()

        page.get_by_role("tab", name="Progress").click()
        page.wait_for_load_state("networkidle")
        expect(page.get_by_text("Technique trends")).to_be_visible()
        expect(page.get_by_text("Next session plan")).to_be_visible()
        expect(page.get_by_text("Target", exact=True).first).to_be_visible()
        expect(page.get_by_text("Pre-send guard")).to_be_visible()
        expect(page.get_by_text("Load cap: easy")).to_be_visible()
        expect(page.get_by_text("Reset before another hard try")).to_be_visible()
        expect(page.get_by_text("Technique readiness").first).to_be_visible()
        expect(page.get_by_text("Next action")).to_be_visible()
        expect(page.get_by_text("Personal benchmarks")).to_be_visible()
        expect(page.get_by_text("Best overall")).to_be_visible()
        expect(page.get_by_text("Cue patterns")).to_be_visible()
        expect(page.get_by_text("Latest cues")).to_be_visible()
        expect(page.get_by_text("Cue usefulness")).to_be_visible()
        expect(page.get_by_text("No cue feedback yet")).to_be_visible()
        expect(page.get_by_text("Practice consistency")).to_be_visible()
        expect(page.get_by_text("Completion", exact=True)).to_be_visible()
        expect(page.get_by_text("Status blocked")).to_be_visible()
        expect(page.get_by_text("Beta memory", exact=True)).to_be_visible()
        expect(page.get_by_text("No beta memory yet")).to_be_visible()
        expect(page.get_by_text("Practice reset session")).to_be_visible()
        expect(page.get_by_text("Attempt comparison")).to_be_visible()
        expect(page.get_by_text("Current trend")).to_be_visible()
        expect(page.get_by_text("Pro history preview")).to_be_visible()
        expect(page.get_by_text("Plan access").first).to_be_visible()

        page.get_by_role("tab", name="Sessions").click()
        page.wait_for_load_state("networkidle")
        expect(page.get_by_text("Local attempts", exact=True)).to_be_visible()
        expect(page.get_by_text("Session review")).to_be_visible()
        expect(page.get_by_text("Focus metric")).to_be_visible()
        expect(page.get_by_text("Primary cue")).to_be_visible()
        expect(page.get_by_text("Timeline", exact=True).first).to_be_visible()
        expect(page.get_by_text("Local evidence")).to_be_visible()
        expect(page.get_by_text("Analysis evidence", exact=True)).to_be_visible()
        expect(page.get_by_text("Privacy boundary")).to_be_visible()
        page.get_by_text("Evidence", exact=True).nth(0).click()
        expect(page.get_by_text("Prepared analysis evidence")).to_be_visible()
        expect(page.get_by_text('"schemaVersion": "movebeta.analysis-evidence-export.v1"')).to_be_visible()
        expect(page.get_by_text("Training log", exact=True)).to_be_visible()
        expect(page.get_by_text("Repeat outcome", exact=True)).to_be_visible()
        expect(page.get_by_text("Cue feedback", exact=True)).to_be_visible()
        page.get_by_label("Project status Repeat").click()
        page.get_by_label("Effort 4").click()
        page.get_by_label("Confidence 5").click()
        page.get_by_label("Repeat outcome Improved").click()
        page.get_by_label("Repeat attempts 2").click()
        page.get_by_label(re.compile("Resolved cue")).first.click()
        page.get_by_text("Useful", exact=True).first.click()
        page.get_by_label("Private training note").fill("Left hip in before the crux.")
        page.get_by_label("Training log tags").fill("board, crux")
        page.get_by_text("Save", exact=True).click()
        page.get_by_role("tab", name="Progress").click()
        page.wait_for_load_state("networkidle")
        expect(page.get_by_text("History filters")).to_be_visible()
        page.get_by_label("vertical", exact=True).click()
        expect(page.get_by_text("1 active filters")).to_be_visible()
        page.get_by_label("Clear progress filters").click()
        expect(page.get_by_text("Project queue")).to_be_visible()
        expect(page.get_by_text("Useful rate")).to_be_visible()
        expect(page.get_by_text("Repeat outcomes", exact=True)).to_be_visible()
        expect(page.get_by_text("Success", exact=True)).to_be_visible()
        expect(page.get_by_text("Improved 1").first).to_be_visible()
        expect(page.get_by_text("Beta memory", exact=True)).to_be_visible()
        expect(page.get_by_text("Stored", exact=True).first).to_be_visible()
        expect(page.get_by_text("Status ready").first).to_be_visible()
        expect(page.get_by_text("Next repeat", exact=True)).to_be_visible()
        expect(page.get_by_text("confidence 5/5")).to_be_visible()
        page.get_by_role("tab", name="Drills").click()
        page.wait_for_load_state("networkidle")
        expect(page.get_by_text("reinforce").first).to_be_visible()
        expect(page.get_by_text("marked useful").first).to_be_visible()
        page.get_by_role("tab", name="Sessions").click()
        page.wait_for_load_state("networkidle")
        expect(page.get_by_text("Coach packet", exact=True).nth(0)).to_be_visible()
        page.get_by_text("Coach packet", exact=True).nth(0).click()
        expect(page.get_by_text("Consent required")).to_be_visible()
        page.get_by_text("Consent", exact=True).nth(0).click()
        expect(page.get_by_text("Coach library")).to_be_visible()
        expect(page.get_by_text("Consented packets")).to_be_visible()
        expect(page.get_by_text("Ready packets")).to_be_visible()
        expect(page.get_by_text("Raw video included: no")).to_be_visible()
        expect(page.get_by_text("Team templates")).to_be_visible()
        expect(page.get_by_text("Privacy-safe packet review")).to_be_visible()
        expect(page.get_by_text("Validation campaign")).to_be_visible()
        expect(page.get_by_text("Real-world cue evidence tracker")).to_be_visible()
        expect(page.get_by_text("1/20")).to_be_visible()
        expect(page.get_by_text("Export status")).to_be_visible()
        page.get_by_text("Export status", exact=True).click()
        expect(page.get_by_text("Prepared validation campaign status")).to_be_visible()
        expect(page.get_by_text('"schemaVersion": "movebeta.coach-validation-workflow.v1"')).to_be_visible()
        expect(page.get_by_text('"rawVideoIncluded": false').last).to_be_visible()
        page.get_by_text("Export library", exact=True).click()
        expect(page.get_by_text("Prepared coach library export")).to_be_visible()
        expect(page.get_by_label("Share prepared export")).to_be_visible()
        expect(page.get_by_text('"schemaVersion": "movebeta.coach-library-export.v1"')).to_be_visible()
        expect(page.get_by_text('"privateNotesIncluded": false')).to_be_visible()
        expect(page.get_by_text('"templates"')).to_be_visible()
        page.get_by_text("Validation seed", exact=True).click()
        expect(page.get_by_text("Prepared cue validation seed")).to_be_visible()
        expect(page.get_by_text('"schemaVersion": "movebeta.cue-validation-study-seed.v1"')).to_be_visible()
        expect(page.get_by_text('"reviewerScoresInvented": false')).to_be_visible()
        expect(page.get_by_text('"reviewTasks"')).to_be_visible()
        page.get_by_text("Clip manifest", exact=True).click()
        expect(page.get_by_text("Prepared cue validation clip manifest")).to_be_visible()
        expect(page.get_by_text('"schemaVersion": "movebeta.cue-validation-clip-intake-manifest.v1"')).to_be_visible()
        expect(page.get_by_text('"coachPacketsIncluded": false')).to_be_visible()
        expect(page.get_by_text('"requiredCoachReviewRows"')).to_be_visible()
        page.get_by_text("Reviewer packet", exact=True).click()
        expect(page.get_by_text("Prepared cue validation reviewer packet")).to_be_visible()
        expect(page.get_by_text('"schemaVersion": "movebeta.cue-validation-reviewer-onboarding.v1"')).to_be_visible()
        expect(page.get_by_text('"rawVideoIncluded": false').last).to_be_visible()
        expect(page.get_by_text('"reviewerScoresInvented": false').last).to_be_visible()
        page.get_by_text("Review worksheet", exact=True).click()
        expect(page.get_by_text("Prepared cue validation worksheet")).to_be_visible()
        expect(page.get_by_text('"schemaVersion": "movebeta.cue-validation-review-worksheet.v1"')).to_be_visible()
        expect(page.get_by_text('"reviewerId": null')).to_be_visible()
        expect(page.get_by_text('"rowCount"')).to_be_visible()
        page.get_by_text("Worksheet CSV", exact=True).click()
        expect(page.get_by_text("Prepared cue validation worksheet CSV")).to_be_visible()
        completed_csv_input = page.get_by_label("Completed cue validation worksheet CSV")
        expect(completed_csv_input).to_have_value(re.compile("worksheetRowId,clipId,packetReportId"))
        expect(completed_csv_input).to_have_value(re.compile("awaiting-real-review"))
        completed_csv_input.fill(complete_validation_csv(completed_csv_input.input_value()))
        page.get_by_text("Build dataset", exact=True).click()
        expect(page.get_by_text("Prepared cue validation dataset")).to_be_visible()
        expect(page.get_by_text("Validation gate: needs data").first).to_be_visible()
        expect(page.get_by_text("At least 20 consented clips are required.").first).to_be_visible()
        expect(page.get_by_text('"schemaVersion": "movebeta.cue-validation-dataset.v1"')).to_be_visible()
        expect(page.get_by_text('"reviewerId": "coach-1"')).to_be_visible()
        page.get_by_text("Coach packet", exact=True).nth(0).click()
        expect(page.get_by_text("Prepared coach packet")).to_be_visible()
        expect(page.get_by_text('"athleteContext"')).to_be_visible()
        expect(page.get_by_text('"drillPractice"')).to_be_visible()
        expect(page.get_by_text('"privateNoteIncluded": false')).to_be_visible()
        expect(page.get_by_text('"noteIncluded": false')).to_be_visible()
        expect(page.get_by_text('"schemaVersion": "movebeta.coach-review.v2"')).to_be_visible()
        expect(page.get_by_text('"cueTrust"')).to_be_visible()
        expect(page.get_by_text('"validationStatus": "needs-review"')).to_be_visible()
        expect(page.get_by_text('"repeatOutcome"')).to_be_visible()

        page.get_by_role("tab", name="Plan").click()
        page.wait_for_load_state("networkidle")
        expect(page.get_by_text("Plan catalog")).to_be_visible()
        expect(page.get_by_text("Current plan").first).to_be_visible()
        expect(page.get_by_text("Upgrade path")).to_be_visible()
        expect(page.get_by_text("Capability matrix")).to_be_visible()
        expect(page.get_by_text("Launch readiness", exact=True)).to_be_visible()
        expect(page.get_by_text("1/3 launch tracks ready")).to_be_visible()
        expect(page.get_by_text("Stakeholder demo", exact=True)).to_be_visible()
        expect(page.get_by_text("Internal native beta", exact=True)).to_be_visible()
        expect(page.get_by_text("Store submission", exact=True)).to_be_visible()
        expect(page.get_by_text("Real cue-validation dataset").first).to_be_visible()
        expect(page.get_by_text("Feature completion", exact=True)).to_be_visible()
        expect(page.get_by_text("Feature completion audit")).to_be_visible()
        expect(page.get_by_text("127/130", exact=True)).to_be_visible()
        expect(page.get_by_text("81/83", exact=True)).to_be_visible()
        expect(page.get_by_text("internal gaps", exact=True)).to_be_visible()
        expect(page.get_by_text("Native device QA evidence").first).to_be_visible()
        expect(page.get_by_text("Model evidence", exact=True)).to_be_visible()
        expect(page.get_by_text("Technical ready")).to_be_visible()
        expect(page.get_by_text("MoveNet execution", exact=True)).to_be_visible()
        expect(page.get_by_text("Model-shaped replay", exact=True)).to_be_visible()
        expect(page.get_by_text("Real climbing validation", exact=True)).to_be_visible()
        expect(page.get_by_text("20 clips and 40 review rows still required")).to_be_visible()
        expect(page.get_by_text("Provider readiness")).to_be_visible()
        expect(page.get_by_text("Provider path needs device proof")).to_be_visible()
        expect(page.get_by_text("web-tfjs-movenet", exact=True).first).to_be_visible()
        expect(page.get_by_text("local-video-fallback", exact=True)).to_be_visible()
        expect(page.get_by_text("native-platform-pose", exact=True)).to_be_visible()
        expect(page.get_by_text("Fallback provider")).to_be_visible()
        expect(page.get_by_text("Native QA evidence kit")).to_be_visible()
        expect(page.get_by_text("device runs", exact=True)).to_be_visible()
        expect(page.get_by_text("workflows", exact=True)).to_be_visible()
        expect(page.get_by_text("Template placeholders are rejected by the native QA validator.")).to_be_visible()
        expect(page.get_by_text("Evidence validator preview")).to_be_visible()
        expect(page.get_by_text("0/2 ready runs").first).to_be_visible()
        expect(page.get_by_text("24 blocking checks")).to_be_visible()
        expect(page.get_by_text("No raw artifact references accepted")).to_be_visible()
        expect(page.get_by_text("Native QA evidence composer")).to_be_visible()
        expect(page.get_by_text("Use composed JSON")).to_be_visible()
        expect(page.get_by_text("Evidence JSON", exact=True)).to_be_visible()
        page.get_by_text("Evidence JSON", exact=True).click()
        expect(page.get_by_text("Prepared native QA evidence JSON")).to_be_visible()
        expect(page.get_by_text('"schemaVersion": "movebeta.native-qa-evidence-composer-export.v1"')).to_be_visible()
        expect(page.get_by_text('"rawArtifactsIncluded": false').last).to_be_visible()
        expect(page.get_by_text("QA runbook", exact=True)).to_be_visible()
        page.get_by_text("QA runbook", exact=True).click()
        expect(page.get_by_text("Prepared native QA runbook")).to_be_visible()
        expect(page.get_by_text('"schemaVersion": "movebeta.native-qa-runbook-packet.v1"')).to_be_visible()
        expect(page.get_by_text('"rawVideoIncluded": false').last).to_be_visible()
        expect(page.get_by_label("Share prepared plan export")).to_be_visible()
        expect(page.get_by_text("Android physical device", exact=True)).to_be_visible()
        expect(page.get_by_text("iOS physical device", exact=True)).to_be_visible()
        expect(page.get_by_text("Physical-device evidence import")).to_be_visible()
        expect(page.get_by_text("Paste JSON")).to_be_visible()
        expect(page.get_by_text("Paste native QA evidence JSON")).to_be_visible()
        expect(page.get_by_text("0 blocking checks", exact=True)).to_be_visible()
        expect(page.get_by_text("Evidence collection plan")).to_be_visible()
        expect(page.get_by_text("20", exact=True).first).to_be_visible()
        expect(page.get_by_text("review rows", exact=True)).to_be_visible()
        expect(page.get_by_text("device checks")).to_be_visible()
        expect(page.get_by_text("pilot sprints")).to_be_visible()
        expect(page.get_by_text("Pilot kit", exact=True)).to_be_visible()
        page.get_by_text("Pilot kit", exact=True).click()
        expect(page.get_by_text("Prepared validation pilot kit")).to_be_visible()
        expect(page.get_by_text('"schemaVersion": "movebeta.validation-pilot-kit.v1"')).to_be_visible()
        expect(page.get_by_text('"rawVideoIncluded": false').last).to_be_visible()
        expect(page.get_by_text('"reviewerScoresInvented": false')).to_be_visible()
        expect(page.get_by_text("Product: Consented climbing clips across wall angles")).to_be_visible()
        expect(page.get_by_text("Release unblock checklist")).to_be_visible()
        expect(page.get_by_text("5", exact=True).first).to_be_visible()
        expect(page.get_by_text("blockers", exact=True).first).to_be_visible()
        expect(page.get_by_text("iOS build verification").first).to_be_visible()
        expect(page.get_by_text("Native device QA evidence").first).to_be_visible()
        expect(page.get_by_text("EAS project binding").first).to_be_visible()
        expect(page.get_by_text("npm run release:eas:strict")).to_be_visible()
        expect(page.get_by_text("EXPO_TOKEN")).to_be_visible()
        expect(page.get_by_text("Prepare packet", exact=True)).to_be_visible()
        page.get_by_text("Prepare packet", exact=True).click()
        expect(page.get_by_text("Prepared release unblock packet")).to_be_visible()
        expect(page.get_by_text('"schemaVersion": "movebeta.release-unblock-packet.v1"')).to_be_visible()
        expect(page.get_by_text('"credentialValuesIncluded": false').last).to_be_visible()
        expect(page.get_by_label("Share prepared plan export")).to_be_visible()
        expect(page.get_by_text("Release evidence packet").first).to_be_visible()
        expect(page.get_by_text("artifacts", exact=True).first).to_be_visible()
        expect(page.get_by_text("commands", exact=True).first).to_be_visible()
        expect(page.get_by_text("iOS toolchain report")).to_be_visible()
        expect(page.get_by_text("Environment template report")).to_be_visible()
        expect(page.get_by_text("Cue validation dataset report")).to_be_visible()
        expect(page.get_by_text("Store credentials report")).to_be_visible()
        expect(page.get_by_text("Evidence packet", exact=True)).to_be_visible()
        page.get_by_text("Evidence packet", exact=True).click()
        expect(page.get_by_text("Prepared release evidence packet")).to_be_visible()
        expect(page.get_by_text('"schemaVersion": "movebeta.release-evidence-packet.v1"')).to_be_visible()
        expect(page.get_by_text('"rawVideoIncluded": false').last).to_be_visible()
        expect(page.get_by_text('"command": "npm run native:ios:doctor"')).to_be_visible()
        expect(page.get_by_text('"command": "npm run release:env:doctor"')).to_be_visible()
        expect(page.get_by_text('"command": "npm run validation:cue:doctor"')).to_be_visible()
        expect(page.get_by_text('"command": "npm run release:credentials:doctor"')).to_be_visible()
        expect(page.get_by_text("Store submission packet", exact=True).first).to_be_visible()
        expect(page.get_by_text("Store packet", exact=True)).to_be_visible()
        expect(page.get_by_text("0/4 credential groups ready")).to_be_visible()
        page.get_by_text("Store packet", exact=True).click()
        expect(page.get_by_text("Prepared store submission packet")).to_be_visible()
        expect(page.get_by_text('"schemaVersion": "movebeta.store-submission-packet.v1"')).to_be_visible()
        expect(page.get_by_text('"trackingEnabled": false')).to_be_visible()
        expect(page.get_by_text('"status": "metadata-ready"').first).to_be_visible()
        page.get_by_text("Credentials packet", exact=True).click()
        expect(page.get_by_text("Prepared store credentials setup packet")).to_be_visible()
        expect(page.get_by_text('"schemaVersion": "movebeta.store-credentials-setup-packet.v1"')).to_be_visible()
        expect(page.get_by_text('"credentialValuesIncluded": false').last).to_be_visible()
        expect(page.get_by_text('"extra.eas.projectId"')).to_be_visible()
        expect(page.get_by_text('"EXPO_TOKEN"')).to_be_visible()
        expect(page.get_by_text("Safety language guard")).to_be_visible()
        expect(page.get_by_text("Copy risk status")).to_be_visible()
        expect(page.get_by_text("Clear", exact=True).last).to_be_visible()
        expect(page.get_by_text("No medical, injury-prevention, or route-safety claims found in checked Plan copy.")).to_be_visible()
        expect(page.get_by_text("Commercial readiness")).to_be_visible()
        expect(page.get_by_text("Commercial checkout not connected")).to_be_visible()
        expect(page.get_by_text("Billing provider adapter")).to_be_visible()
        expect(page.get_by_text("Paid plan product mappings")).to_be_visible()
        expect(page.get_by_text("0/2", exact=True)).to_be_visible()
        expect(page.get_by_text("No credential values in config")).to_be_visible()
        expect(page.get_by_text("Commercial packet", exact=True)).to_be_visible()
        page.get_by_text("Commercial packet", exact=True).click()
        expect(page.get_by_text("Prepared commercial readiness packet")).to_be_visible()
        expect(page.get_by_text('"schemaVersion": "movebeta.commercial-readiness-packet.v1"')).to_be_visible()
        expect(page.get_by_text('"paymentDataIncluded": false')).to_be_visible()
        expect(page.get_by_text('"receiptValuesIncluded": false')).to_be_visible()

        page.get_by_role("tab", name="Privacy").click()
        page.wait_for_load_state("networkidle")
        expect(page.get_by_text("No upload by default")).to_be_visible()
        expect(page.get_by_text("Airplane-mode readiness")).to_be_visible()
        page.get_by_text("Check", exact=True).click()
        expect(page.get_by_text("Ready for offline analysis")).to_be_visible()
        expect(page.get_by_text("Diagnostics", exact=True)).to_be_visible()
        page.get_by_text("Prepare", exact=True).click()
        expect(page.get_by_text("Privacy-safe support packet")).to_be_visible()
        expect(page.get_by_text('"excludedArtifacts"')).to_be_visible()
        expect(page.get_by_text("Data portability")).to_be_visible()
        page.get_by_text("Backup", exact=True).click()
        expect(page.get_by_text("Local backup JSON")).to_be_visible()
        expect(page.get_by_role("textbox", name="Local backup JSON")).to_have_value(re.compile('"schemaVersion"'))
        expect(page.get_by_role("textbox", name="Local backup JSON")).to_have_value(re.compile('"drillPractice"'))
        page.get_by_text("Restore backup", exact=True).click()
        expect(page.get_by_text("Status: restored")).to_be_visible()
        expect(page.get_by_text("Reports restored:")).to_be_visible()
        expect(page.get_by_text("Drill practice records restored:")).to_be_visible()

        page.get_by_role("tab", name="Sessions").click()
        page.wait_for_load_state("networkidle")
        page.get_by_label("Delete Vertical sequence repeat").first.click()
        expect(page.get_by_text("Local deletion receipt")).to_be_visible()
        expect(page.get_by_text("Private training log: deleted")).to_be_visible()
        expect(page.get_by_text("Coach consent record: deleted")).to_be_visible()
        expect(page.get_by_text("Video left device: no").last).to_be_visible()

        browser.close()

    if page_errors:
      raise AssertionError(f"Page errors: {page_errors}")
    if console_errors:
      ignored = [item for item in console_errors if "favicon" not in item.lower()]
      if ignored:
        raise AssertionError(f"Console errors: {ignored}")


if __name__ == "__main__":
    main()
